name = "Immortal"
uuid = "7e70e6b1-cd01-4477-bffb-6df788447f4e"
authors = ["Dmitrii Shevelev"]
version = "0.1.0"

[deps]
AMQPClient = "79c8b4cd-a41a-55fa-907c-fab5288e1383"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
